Fix #85, add CmdCode to sch_lab_table
nasa/sch_lab pull request #86
Opened 2021-09-01 21:57 UTC by jphickey

**Describe the contribution**
Allows the command/function code to be specified in the messages generated by SCH_LAB.  This allows it to be used for testing apps that require a specific function code in the internal wakeup message.

Fixes #85

**Testing performed**
Validated that the feature works by using it to test BP app (which requires a specific code in it's wakeup MID)

**Expected behavior changes**
SCH_LAB now supports testing apps that require a specific function code in the generated wake up message

**System(s) tested on**
Ubuntu

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

2021-09-02 12:45 UTC, skliper commented
Add to the default table?  More obvious to the user if the element is at minimum described there or provides an example (can be commented out).

2021-09-07 20:13 UTC, pepepr08 requested changes
Modify table file to add example on how to set command code (or update current entries to include the CC).

2021-09-08 16:13 UTC, astrogeco commented
[CCB:2021-09-08](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-September-08-2021) APPROVED

2021-09-08 17:08 UTC, pepepr08 approved these changes

2021-09-08 18:22 UTC, merged